pull_parameters: true

# select a kernel if pull_parameters=true and you want to pull the config from sheet
target_kernel: Kernel_4


# -- auto fill below -- #
live_pnl_report_start:
  start_day: "2025_08_25"
  start_time: "09:23:00"

pairs: [[DOGEUSDT, AVAXUSDT], [UNIUSDT, AVAXUSDT], [DOTUSDT, AVAXUSDT], [BNBUSDT, TRXUSDT], [DOTUSDT, DOGEUSDT]]
configs: [0.25#50#0.5#0#2000#5, -0.25#75#0.75#0#1200#9, -0.375#50#0.5#0.25#2200#5, 0#300#0.9999#0#2600#9, 0#100#0.75#0#4100#5]
trader_ids: [trader_624, trader_625, trader_626, trader_627, trader_628]
model_fitting_dates: [['2025_07_01', '2025_08_15'], ['2025_07_01', '2025_08_15'], ['2025_07_01', '2025_08_15'], ['2025_07_01', '2025_08_15'], ['2025_07_01', '2025_08_15']]

# --------------------- #

download_binance_1m_market_data: false # used for charts
download_internal_market_data: false
sync_internal_market_data: false
run_daily_backtest: true

signal_angle:
  rolling_angle_windows_in_days: 4

cointegration_test:
  half_life_window: 300
  half_life_step: 100



# python3 -m prod_report_module prod_report
