ssh:
  host: 13.231.38.207
  port: 22
  user: ubuntu
  key: ~/.ssh/id_rsa.pub   # or null if using password
  password: null           # leave null to be prompted at runtime

paths:
  remote_dir: /path/on/server
  local_dir: /path/on/local

options:
  recursive: true